name: Default configuration
base: q35.yaml

machine:
  memory: 4G
  vcpu: 8
  # Turn on BIOS output and performance measurement
  debug: No
  # Turn on hypervisor to lower CPU usage (Hyper-V is used for Windows)
  hypervisor: Yes

objects:
  - class: qxl
  - class: spice-agent
  - class: qemu-guest-agent
  - class: usb-tablet

  - class: virtio-network
    backend: uip
    mac: 00:50:00:11:22:33

  - class: ahci-cdrom 
    image: /data/ubuntu-21.10-desktop-amd64.iso
  
  - class: ahci-cdrom
    image: /data/virtio.iso

  - class: virtio-block
    image: /data/win11.qcow2
    snapshot: No

  - class: virtio-block
    image: /data/empty.qcow2
    snapshot: No

  # - class: vfio-pci
  #   sysfs: /sys/bus/mdev/devices/c2e088ba-954f-11ec-8584-525400666f2b
  #   debug: Yes
