name: Default configuration
base: q35.yaml

machine:
  memory: 8G
  vcpu: 4
  debug: Yes

objects:
  # - class: ahci-cdrom
  #   image: /data/virtio.iso
  
  # - class: ahci-disk
  #   image: /data/empty.qcow2

  - class: virtio-block
    image: /data/hd.qcow2

  # - name: nvidia-vgpu
  #   class: vfio-pci
  #   parent: pci-host
  #   debug: No
  #   sysfs: /sys/bus/mdev/devices/c2e088ba-954f-11ec-8584-525400666f2b
