name: Default configuration
base: q35.yaml

machine:
  memory: 8G
  vcpu: 4
  debug: No

objects:
  # - class: ahci-cdrom
  #   image: /data/win10_21h1.iso
  
  # - class: ahci-disk
  #   image: /data/empty.qcow2

  - class: virtio-block
    image: /data/hd.qcow2
    readonly: No
