name: Default configuration
base: q35.yaml

machine:
  memory: 8G
  vcpu: 4
  debug: No

objects:
  # - class: ahci-cdrom
  #   image: /mnt/iso/virtio.iso
  
  # - class: ahci-disk
  #   image: /data/empty.qcow2
  #   snapshot: No

  - class: virtio-block
    image: /mnt/images/6019019526e086323a3dbce6_6d75ef18-671d-47bf-a0a2-35a36764bdf8.qcow2
    snapshot: Yes

  # - name: nvidia-vgpu
  #   class: vfio-pci
  #   parent: pci-host
  #   debug: Yes
  #   sysfs: /sys/bus/mdev/devices/c2e088ba-954f-11ec-8584-525400666f2b
