name: q35-machine

machine:
  memory: 2G
  vcpu: 4
  bios: ../share/bios-256k.bin

objects:
  - class: system-root
    children:
      - pci-host
      - firmware-config
      - dummy-device
      - debug-console
      
  - class: pci-host
    children:
      - ich9-lpc
      - ahci-host
      - ich9-smbus
      - qxl
      - virtio-console
      - virtio-block
      - virtio-network

  - class: virtio-console
    children:
      - spice-agent

  - class: ich9-lpc
    children:
      - cmos
      - keyboard
      - pc-speaker
  
  - class: ahci-host
    children:
      - ahci-cdrom
      - ahci-disk
  
  - class: qxl
    rom: ../share/vgabios-qxl.bin

  - class: vga
    rom: ../share/vgabios-stdvga.bin
