name: q35-machine

machine:
  memory: 4G
  vcpu: 4
  bios: ../share/bios-256k.bin

objects:
# Use the old name pci-host instead of q35-host for compatibility
  - class: q35-host

# PCI devices connected to PCI Host
  - class: ich9-hda
  - class: ich9-lpc
  - class: ich9-ahci

# I/O devices connected to ICH9 LPC
  - class: cmos
  - class: debug-console
  - class: dummy-device
  - class: firmware-config
  - class: kvm-clock
  - class: ps2

# codec device connected to ICH9 HDA
  - class: hda-duplex
