name: Default configuration
base: q35.yaml

machine:
  memory: 4G
  vcpu: 8
  # Turn on BIOS output and performance measurement
  debug: No
  # Turn on hypervisor to lower CPU usage (Hyper-V is used for Windows)
  hypervisor: Yes

objects:
  - class: cmos
    # gmtime for linux, localtime for windows
    rtc: gmtime
    
  - class: qxl
  - class: spice-agent
  - class: qemu-guest-agent
  - class: usb-tablet
  # - class: usb-midi
  # - class: usb-wacom

  - class: virtio-network
    backend: uip
    mac: 00:50:00:11:22:33
    map: tcp:0.0.0.0:8022-:22

  - class: ahci-cdrom 
    image: /data/ubuntu-21.10-desktop-amd64.iso
  
  - class: ahci-cdrom
    image: /data/virtio.iso

  - class: virtio-block
    image: /data/empty.qcow2
    snapshot: No

  # - class: virtio-block
  #   image: /data/win11.qcow2
  #   snapshot: No

  # - class: virtio-fs
  #   path: /tmp/fuse
  #   disk_name: mvisor-fs
  #   disk_size: 2G
  #   inode_count: 200

  # - class: vfio-pci
  #   sysfs: /sys/bus/mdev/devices/c2e088ba-954f-11ec-8584-525400666f2b
  #   debug: Yes
